### ISSUE TITLE
lens dumps everything under 'default'

### ISSUE THREAD

**Issue by larsks** [uty/haproxy-augeas-lens#1]
I was briefly trying this out -- because I need to parse an haproxy.cfg and was trying to avoid reinventing the wheel -- but it looks like this lens dumps all the "listen" sections at least under the 'default' section.  That is, after loading an haproxy.cfg with a `global`, `default`, and several `listen` sections, I get:

```
augtool> ls /files/etc/haproxy/haproxy.cfg/
global/ = (none)
defaults/ = (none)
```

...and under `defaults/`:

```
log/ = (none)
mode[1] = tcp
tcplog[1] = true
redispatch = true
retries = 3
timeout_connect = 5s
timeout_client[1] = 600s
timeout_server[1] = 600s
listen[1] = amqp
bind[1]/ = (none)
bind[2]/ = (none)
mode[2] = tcp
clitcpka = true
srvtcpka = true
stick_on/ = (none)
stick-table/ = (none)
timeout_client[2] = 900m
timeout_server[2] = 900m
server[1]/ = (none)
server[2]/ = (none)
server[3]/ = (none)
listen[2] = cinder-api
bind[3]/ = (none)
bind[4]/ = (none)
bind[5]/ = (none)
mode[3] = tcp
tcplog[2] = true
server[4]/ = (none)
server[5]/ = (none)
server[6]/ = (none)
```

...etc.

That seems wrong.

**Comment by uty** [comment]
Hi,

Thank you for pointing this out. We never stumbled upon this, because we were using the lens only for writing into config and never actually reading it using augeas. 
Should be fixed now.
